language: bash
os: windows
env:
 - CONFIG=Release PLATFORM=x64
script:
 - dir "c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC"
 - dir "c:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC"
 - "c:\Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe"
branches:
  only:
  - master
